"""CLI flow: create a document-request against an existing DATEV Vorgangsmappe.

Seam: `run_create_request(args, *, klardaten_client, magic_link_secret,
magic_link_base_url, now) -> str` — orchestrates {validate args → upload
letter into VGM → generate HMAC token → compose magic-link URL}, returns
the URL. `__main__.py` calls this and prints the URL to stdout.

Args are validated via Pydantic so failure messages are uniform whether
they come from the CLI or a future test/programmatic caller.

This module does NOT:
- read env vars itself — `__main__` reads them (fail-fast on missing /
  weak secret / non-https base URL) and injects them here
- start an HTTP server, serve `/r/<token>`, or handle the client's submit
  (next slice)
- send email or otherwise notify the client (out of scope)
- deduplicate or guard against re-running (a second invocation creates a
  second `_request_letter_*.txt` inside the VGM — that's a feature, not a
  bug: each run is auditable)
- verify-after-upload via GET (relies on `UploadResult.success`; future
  slice can add a roundtrip check)
"""

from __future__ import annotations

import tempfile
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field, ValidationInfo, field_validator
from pydantic_core import PydanticCustomError

from belegmeister.datev.upload import BinderClient, upload_to_binder
from belegmeister.magic_link.token import generate_token
from belegmeister.request_format import (
    RequestLetter,
    has_sentinel_collision,
    is_blank,
    is_email_like,
    is_single_line,
    serialize_request_letter,
)
from belegmeister.vgm_files import request_letter_filename

# Maximum lifetime of a magic-link from creation. Tax docs are either
# submitted within a week or forgotten; an expired link is cheaply
# regenerated by the SB. Short exposure limits credential-leak blast
# radius. Compared as `total_seconds()`, not `.days`, so a 7-day-and-one-
# second TTL is rejected (floor-to-days would silently extend lifetime).
MAX_TTL_DAYS = 7

# User-facing message for a malformed email in `to` / `cc`. Raised via
# `PydanticCustomError` (NOT `ValueError`) so Pydantic does not prepend
# the "Value error, " envelope to a message that reaches an end user.
# One source of truth between the `to` and `cc` validators.
_EMAIL_FORMAT_MSG = "Bitte eine korrekte E-Mail-Adresse eingeben."


class UploadFailed(Exception):
    """The letter could not be stored in the target VGM.

    Distinct from `InvalidUploadTarget` (which means "the target is not
    a valid Vorgangsmappe"): `UploadFailed` means the target was fine but
    the byte transfer or server-side accept did not succeed. A future
    HTTP handler should map these to different statuses.

    Message embeds `vgm_id` + `reason` so a single log line is
    self-describing — same pattern as Slice-1's `InvalidUploadTarget`.
    """

    def __init__(self, *, vgm_id: str, reason: str) -> None:
        self.vgm_id = vgm_id
        self.reason = reason
        super().__init__(f"upload to {vgm_id} failed: {reason}")


class CreateRequestArgs(BaseModel):
    """Validated arguments for a ``create-request`` invocation.

    The single Pydantic gate for both the CLI (``__main__``) and the SB
    web form (``belegmeister.sb.app``). Field-level validators wrap the
    shared predicates from ``belegmeister.request_format`` (``is_blank``,
    ``is_single_line``, ``has_sentinel_collision``) so the SAME rule
    decides for every caller — the codec layer then re-checks with its
    own exception type (``RequestLetterMalformed``) for defense in depth.
    See ``CLAUDE.md`` / ``AGENTS.md`` "Single source of truth for
    cross-layer logic".

    Must be constructed via
    ``CreateRequestArgs.model_validate(data, context={"now": now})`` —
    the ``expires_at`` validator reads ``now`` from the validation
    context so tests can pin a deterministic clock; constructing
    without that context raises ``ValueError`` from the validator.

    Attributes:
        vgm_id: The DATEV Vorgangsmappe GUID (NOT the UI
            Dokumentnummer — the SB form resolves number → GUID before
            constructing this).
        to: Recipient email used as the ``To:`` header on the wire
            letter. Stripped, must be a single line, must be non-blank.
        cc: Optional Cc email. Stripped; empty allowed. If non-empty
            it must be a single line.
        subject: Email subject. Stripped, single line, non-blank.
        body: Letter body. Kept verbatim — leading/trailing blank lines
            and indentation are preserved on purpose. Must be non-blank
            and must not contain a line starting with the request-marker
            sentinel.
        questions: Optional list of single-line questions for the
            Mandant. Each question is stripped; blanks and sentinel
            collisions raise ``ValueError``. Order is preserved.
        expires_at: Magic-link hard expiry. Must be in the future of
            the validation context's ``now`` AND within
            ``MAX_TTL_DAYS`` (7) of it.
    """

    vgm_id: str = Field(min_length=1)
    to: str
    cc: str = ""
    subject: str
    body: str
    questions: list[str] = Field(default_factory=list)
    expires_at: datetime

    # Validators wrap the shared request_format predicates (one source
    # of truth) and raise ValueError -> ValidationError. The codec's
    # _reject_* helpers wrap the SAME predicates and raise
    # RequestLetterMalformed. See CLAUDE.md "Single source of truth".

    @field_validator("subject")
    @classmethod
    def _required_single_line_header(cls, v: str) -> str:
        # Strip: leading/trailing whitespace on a header is meaningless
        # and parse_request_letter strips it anyway — pre-strip keeps the
        # round-trip exact (codec B12).
        stripped = v.strip()
        if is_blank(stripped):
            raise ValueError("must not be blank")
        if not is_single_line(stripped):
            raise ValueError("must be a single line (no newline / CR)")
        return stripped

    @field_validator("to")
    @classmethod
    def _required_email_to(cls, v: str) -> str:
        stripped = v.strip()
        if is_blank(stripped):
            raise ValueError("must not be blank")
        if not is_single_line(stripped):
            raise ValueError("must be a single line (no newline / CR)")
        if not is_email_like(stripped):
            raise PydanticCustomError("email_format", _EMAIL_FORMAT_MSG)
        return stripped

    @field_validator("cc")
    @classmethod
    def _optional_single_line_cc(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            return stripped
        if not is_single_line(stripped):
            raise ValueError("must be a single line (no newline / CR)")
        if not is_email_like(stripped):
            raise PydanticCustomError("email_format", _EMAIL_FORMAT_MSG)
        return stripped

    @field_validator("body")
    @classmethod
    def _non_blank_body_verbatim(cls, v: str) -> str:
        # NOT stripped by design: the SB's body reaches the VGM
        # byte-for-byte (intentional leading/trailing blank lines,
        # indentation). Only a wholly-blank body is rejected.
        if is_blank(v):
            raise ValueError("must not be blank")
        if has_sentinel_collision(v):
            raise ValueError(
                "must not contain a line starting with the reserved request marker"
            )
        return v

    @field_validator("questions")
    @classmethod
    def _clean_questions(cls, v: list[str]) -> list[str]:
        cleaned: list[str] = []
        for index, question in enumerate(v):
            # Deliberate strip: a question is single-line; surrounding
            # whitespace is meaningless (unlike body, this is NOT a
            # verbatim field). Empty list stays empty (zero questions ok).
            stripped = question.strip()
            if is_blank(stripped):
                raise ValueError(f"question {index} must not be blank")
            if not is_single_line(stripped):
                raise ValueError(
                    f"question {index} must be a single line (no newline / CR)"
                )
            if has_sentinel_collision(stripped):
                raise ValueError(
                    f"question {index} must not contain the reserved request marker"
                )
            cleaned.append(stripped)
        return cleaned

    @field_validator("expires_at")
    @classmethod
    def _must_be_in_future(cls, v: datetime, info: ValidationInfo) -> datetime:
        if not info.context or "now" not in info.context:
            raise ValueError(
                "validation context must include 'now' (datetime); "
                "caller should pass `context={'now': now}`"
            )
        now = info.context["now"]
        if not isinstance(now, datetime):
            raise ValueError("context['now'] must be a datetime")
        if v <= now:
            raise ValueError(
                f"expires_at must be in the future "
                f"(got {v.isoformat()}, now is {now.isoformat()})"
            )
        if (v - now).total_seconds() > MAX_TTL_DAYS * 86400:
            raise ValueError(
                f"expires_at exceeds {MAX_TTL_DAYS}-day TTL cap "
                f"(got {(v - now).total_seconds() / 86400:.2f} days)"
            )
        return v


def run_create_request(
    args: CreateRequestArgs,
    *,
    klardaten_client: BinderClient,
    magic_link_secret: str,
    magic_link_base_url: str,
    now: datetime,
) -> str:
    """Orchestrate creating a document request and return the magic-link URL.

    The shared 4a "core" called by the CLI (``__main__._cmd_create_request``)
    and the SB web form (``belegmeister.sb.app.create_request_page``).
    Steps, in order:

    1. Build the ISO-stamped letter filename via
       ``vgm_files.request_letter_filename`` (single source of truth
       shared with the magic-link page's reader filter).
    2. Construct a ``RequestLetter`` from the validated args and
       serialize it through ``request_format.serialize_request_letter``
       (which re-checks header / body invariants).
    3. Write the wire text to a tempfile inside a
       ``TemporaryDirectory`` (auto-deleted on exit) and call
       ``datev.upload.upload_to_binder``, which performs the two-call
       klardaten attach (``POST /document-files`` → ``POST
       /documents/{vgm_id}/structure-items``).
    4. Mint an HMAC magic-link token via
       ``magic_link.token.generate_token`` and compose
       ``<base_url>/r/<token>``.

    Args:
        args: Already-validated ``CreateRequestArgs``. The caller is
            responsible for ``model_validate(..., context={"now": now})``
            — re-validating here would be redundant.
        klardaten_client: Any ``BinderClient`` (in production a
            ``KlardatenClient``; in tests a fake matching the
            protocol).
        magic_link_secret: The HMAC signing key. Validated upstream
            (``env_validation.validate_secret``); this function does
            not re-check.
        magic_link_base_url: Public origin for ``/r/<token>`` URLs.
            Trailing ``/`` is stripped during composition; the caller's
            validator already enforced the ``https://`` /
            ``http://localhost`` prefix rule.
        now: The wall-clock used to stamp the letter filename. Same
            value should appear in the validation context that produced
            ``args``, so the filename and ``args.expires_at`` are
            consistent.

    Returns:
        The complete magic-link URL ready to forward to the Mandant —
        ``"<base_url>/r/<token>"``. Each invocation produces a fresh
        token AND a fresh letter file inside the binder; re-running
        does NOT replace the previous letter (each run is auditable).

    Raises:
        UploadFailed: The target VGM exists and is a Vorgangsmappe but
            the byte transfer or server-side accept did not succeed
            (HTTP 5xx, transport error, malformed response). Message
            embeds ``vgm_id`` + ``reason``.

        ``upload_to_binder`` may also propagate
        ``datev.upload.InvalidUploadTarget`` (the binder is not a
        Vorgangsmappe, or the GUID returns 404) — that exception is
        raised here without modification.

        ``serialize_request_letter`` may raise
        ``request_format.RequestLetterMalformed`` if a header or body
        slipped past the boundary (defense-in-depth; should not happen
        when ``CreateRequestArgs`` was correctly validated).

    Side effects:
        * Writes a temporary file under the OS tempdir; the tempdir is
          removed on return (success or failure).
        * Makes one HTTP ``GET`` and (on a valid target) two HTTP
          ``POST``s to the klardaten gateway, leaving a new
          structure-item inside the binder on success.
        * Computes one HMAC-SHA256 over the token payload bytes.
    """
    iso_now = now.astimezone(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    filename = request_letter_filename(iso_now)
    letter = RequestLetter(
        to=args.to,
        cc=args.cc,
        subject=args.subject,
        body=args.body,
        questions=tuple(args.questions),
    )
    content = serialize_request_letter(letter)
    with tempfile.TemporaryDirectory() as tmpdir:
        letter_path = Path(tmpdir) / filename
        letter_path.write_text(content, encoding="utf-8")
        result = upload_to_binder(letter_path, args.vgm_id, klardaten_client)
    if not result.success:
        raise UploadFailed(vgm_id=args.vgm_id, reason=result.error or "unknown error")
    token = generate_token(
        vgm_id=args.vgm_id, expires_at=args.expires_at, secret=magic_link_secret
    )
    return f"{magic_link_base_url.rstrip('/')}/r/{token}"
