"""CLI flow: create a document-request against an existing DATEV Vorgangsmappe.

Seam: `run_create_request(args, *, klardaten_client, magic_link_secret,
magic_link_base_url, now) -> str` — orchestrates {validate args → upload
letter into VGM → generate HMAC token → compose magic-link URL}, returns
the URL. `__main__.py` calls this and prints the URL to stdout.

Args are validated via Pydantic so failure messages are uniform whether
they come from the CLI or a future test/programmatic caller.

This module does NOT:
- read env vars itself — `__main__` reads them (fail-fast on missing /
  weak secret / non-https base URL) and injects them here
- start an HTTP server, serve `/r/<token>`, or handle the client's submit
  (next slice)
- send email or otherwise notify the client (out of scope)
- deduplicate or guard against re-running (a second invocation creates a
  second `_request_letter_*.md` inside the VGM — that's a feature, not a
  bug: each run is auditable)
- verify-after-upload via GET (relies on `UploadResult.success`; future
  slice can add a roundtrip check)
"""

from __future__ import annotations

import tempfile
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field, ValidationInfo, field_validator

from belegmeister.datev.upload import BinderClient, upload_to_binder
from belegmeister.magic_link.token import generate_token

# Maximum lifetime of a magic-link from creation. Tax docs are either
# submitted within a week or forgotten; an expired link is cheaply
# regenerated by the SB. Short exposure limits credential-leak blast
# radius. Compared as `total_seconds()`, not `.days`, so a 7-day-and-one-
# second TTL is rejected (floor-to-days would silently extend lifetime).
MAX_TTL_DAYS = 7


class UploadFailed(Exception):
    """The letter could not be stored in the target VGM.

    Distinct from `InvalidUploadTarget` (which means "the target is not
    a valid Vorgangsmappe"): `UploadFailed` means the target was fine but
    the byte transfer or server-side accept did not succeed. A future
    HTTP handler should map these to different statuses.

    Message embeds `vgm_id` + `reason` so a single log line is
    self-describing — same pattern as Slice-1's `InvalidUploadTarget`.
    """

    def __init__(self, *, vgm_id: str, reason: str) -> None:
        self.vgm_id = vgm_id
        self.reason = reason
        super().__init__(f"upload to {vgm_id} failed: {reason}")


class CreateRequestArgs(BaseModel):
    """Validated CLI arguments.

    Constructed via `CreateRequestArgs.model_validate(data, context={"now": now})`
    so `expires_at` can be checked against an injectable wall-clock.
    """

    vgm_id: str = Field(min_length=1)
    letter_text: str = Field(min_length=1)
    expires_at: datetime

    @field_validator("expires_at")
    @classmethod
    def _must_be_in_future(cls, v: datetime, info: ValidationInfo) -> datetime:
        if not info.context or "now" not in info.context:
            raise ValueError(
                "validation context must include 'now' (datetime); "
                "caller should pass `context={'now': now}`"
            )
        now = info.context["now"]
        if not isinstance(now, datetime):
            raise ValueError("context['now'] must be a datetime")
        if v <= now:
            raise ValueError(
                f"expires_at must be in the future "
                f"(got {v.isoformat()}, now is {now.isoformat()})"
            )
        if (v - now).total_seconds() > MAX_TTL_DAYS * 86400:
            raise ValueError(
                f"expires_at exceeds {MAX_TTL_DAYS}-day TTL cap "
                f"(got {(v - now).total_seconds() / 86400:.2f} days)"
            )
        return v


def run_create_request(
    args: CreateRequestArgs,
    *,
    klardaten_client: BinderClient,
    magic_link_secret: str,
    magic_link_base_url: str,
    now: datetime,
) -> str:
    """Orchestrate: upload letter file → generate token → compose URL.

    Returns the magic-link URL (caller prints to stdout).
    """
    iso_now = now.astimezone(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    filename = f"_request_letter_{iso_now}.md"
    with tempfile.TemporaryDirectory() as tmpdir:
        letter_path = Path(tmpdir) / filename
        letter_path.write_text(args.letter_text, encoding="utf-8")
        result = upload_to_binder(letter_path, args.vgm_id, klardaten_client)
    if not result.success:
        raise UploadFailed(vgm_id=args.vgm_id, reason=result.error or "unknown error")
    token = generate_token(
        vgm_id=args.vgm_id, expires_at=args.expires_at, secret=magic_link_secret
    )
    return f"{magic_link_base_url.rstrip('/')}/r/{token}"
